---
- name: Backup Devices
  hosts: routers
  gather_facts: false
  vars:
    report_server: reports
    # web_path: /tmp/backup
    web_path: /var/www/html/backups/

  tasks:
    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        type: full
        data_store:
          local: "/tmp/network_local_backup"

    - name: list files in /tmp
      delegate_to: localhost
      run_once: true
      ansible.builtin.command:
        cmd: ls /tmp/network_local_backup

    - name: Copy backup to backup server
      become: true
      delegate_to: "{{ report_server }}"
      block:
        - name: Build report server
          ansible.builtin.include_role:
            name: "{{ item }}"
          loop:
            - demo.patching.report_server
            - demo.patching.build_report_network

        - name: Create a backup directory if it does not exist
          ansible.builtin.file:
            path: "{{ web_path }}"
            state: directory
            mode: '0755'

        - name: Copy backup file
          ansible.builtin.copy:
            src: "/tmp/network_local_backup/{{ inventory_hostname }}.txt"
            dest: "{{ web_path }}"

...
