---
- name: Create network reports server
  hosts: reports
  become: true

  tasks:
    - name: Build report server
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - demo.patching.report_server

    - name: Create a backup directory if it does not exist
      run_once: true
      ansible.builtin.file:
        path: "/var/www/html/backups"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'